version: 3.0.{build}

configuration:

- Debug

platform:

- x64

image:

- Visual Studio 2017
- Visual Studio 2015

# Disable build through solution file
build: off

# Build through commands in script below
test_script:

- ps: >-

    echo $env:APPVEYOR_BUILD_WORKER_IMAGE

    if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017")
    {
        msbuild /t:Build tests\msvc150\linalg-test.vcxproj
        tests\msvc150\bin\linalg-test-Debug-x64.exe
    }
    if($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015")
    {
        msbuild /t:Build tests\msvc140\linalg-test.vcxproj
        tests\msvc140\bin\linalg-test-Debug-x64.exe
    }