sudo: false
language: cpp
matrix:
  include:
    - env: COMPILER=g++-5
      addons: { apt: { packages: ["g++-5"], sources: ["ubuntu-toolchain-r-test"] } }  
    - env: COMPILER=g++-6
      addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }
    - env: COMPILER=clang++-3.7
      addons: { apt: { packages: ["clang-3.7"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.7"] } }
    
    
install:
  - export CXX=${COMPILER}
  - ${CXX} --version
  - ${CXX} -v

script: 
  cd samples;
  make;
  ./linalg-test;
